"""The nine repository ports. Narrow, CRUD, no `SELECT` leaks past here."""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from interviewer_core.domain.entities import (
    Area,
    Artifact,
    InterviewInvite,
    InterviewReport,
    Persona,
    Session,
    Turn,
    User,
    WorkflowRun,
)


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...
    async def get_by_email(self, email: str) -> User | None: ...


class AreaRepository(Protocol):
    async def add(self, area: Area) -> None: ...
    async def get(self, area_id: str) -> Area | None: ...
    async def list(self) -> Sequence[Area]: ...


class PersonaRepository(Protocol):
    async def add(self, persona: Persona) -> None: ...
    async def get(self, persona_id: str) -> Persona | None: ...
    async def latest_published(self, area_id: str) -> Persona | None: ...


class InviteRepository(Protocol):
    async def add(self, invite: InterviewInvite) -> None: ...
    async def get_by_slug(self, slug: str) -> InterviewInvite | None: ...

    async def claim(self, slug: str, now: datetime) -> InterviewInvite | None:
        """Atomically check `is_claimable` and increment `used_count`.

        Returns the claimed invite, or `None` if the slug does not exist.
        Two candidates opening the last slot at once must not both succeed --
        the adapter's job, not the caller's.
        """
        ...

    async def delete(self, invite_id: str) -> None: ...


class SessionRepository(Protocol):
    async def add(self, session: Session) -> None: ...
    async def get(self, session_id: str) -> Session | None: ...
    async def update(self, session: Session) -> None: ...


class TurnRepository(Protocol):
    async def add(self, turn: Turn) -> None: ...
    async def list_for_session(self, session_id: str) -> Sequence[Turn]: ...


class ArtifactRepository(Protocol):
    async def add(self, artifact: Artifact) -> None: ...
    async def get(self, artifact_id: str) -> Artifact | None: ...


class ReportRepository(Protocol):
    async def add(self, report: InterviewReport) -> None: ...
    async def get_for_session(self, session_id: str) -> InterviewReport | None: ...


class RunRepository(Protocol):
    async def add(self, run: WorkflowRun) -> None: ...
    async def get(self, run_id: str) -> WorkflowRun | None: ...
    async def get_by_idempotency_key(self, idempotency_key: str) -> WorkflowRun | None: ...
    async def update(self, run: WorkflowRun) -> None: ...
