"""initial schema

Revision ID: 3b4b8b71f076
Revises:
Create Date: 2026-09-08 13:49:29.120751
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3b4b8b71f076"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_areas_slug"), "areas", ["slug"], unique=True)
    op.create_table(
        "artifacts",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mime", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("uri", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("checksum", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artifacts_session_id"), "artifacts", ["session_id"], unique=False)
    op.create_table(
        "interview_invites",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("persona_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("passkey_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_sessions", sa.Integer(), nullable=False),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_invites_persona_id"), "interview_invites", ["persona_id"], unique=False
    )
    op.create_index(op.f("ix_interview_invites_slug"), "interview_invites", ["slug"], unique=True)
    op.create_table(
        "interview_reports",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("persona_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scores_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_reports_persona_id"), "interview_reports", ["persona_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_reports_session_id"), "interview_reports", ["session_id"], unique=True
    )
    op.create_table(
        "personas",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("area_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("voice", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("llm_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("llm_model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("greeting_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("intake_prompt_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("farewell_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("questions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("min_coverage", sa.Float(), nullable=False),
        sa.Column("max_questions", sa.Integer(), nullable=False),
        sa.Column("rubric", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("area_id", "version", name="uq_personas_area_version"),
    )
    op.create_index(op.f("ix_personas_area_id"), "personas", ["area_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invite_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("persona_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("candidate_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name_confidence", sa.Float(), nullable=True),
        sa.Column("coverage_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_invite_id"), "sessions", ["invite_id"], unique=False)
    op.create_index(op.f("ix_sessions_persona_id"), "sessions", ["persona_id"], unique=False)
    op.create_index("ix_sessions_persona_phase", "sessions", ["persona_id", "phase"], unique=False)
    op.create_index("ix_sessions_started_at", "sessions", ["started_at"], unique=False)
    op.create_table(
        "turns",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("question_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("transcript", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("audio_artifact_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("usage_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "index", name="uq_turns_session_index"),
    )
    op.create_index(op.f("ix_turns_session_id"), "turns", ["session_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "workflow_runs",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workflow", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("idempotency_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_runs_idempotency_key"), "workflow_runs", ["idempotency_key"], unique=True
    )
    op.create_table(
        "workflow_step_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("output_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "name", name="uq_step_records_run_name"),
    )
    op.create_index(
        op.f("ix_workflow_step_records_run_id"), "workflow_step_records", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_step_records_run_id"), table_name="workflow_step_records")
    op.drop_table("workflow_step_records")
    op.drop_index(op.f("ix_workflow_runs_idempotency_key"), table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_turns_session_id"), table_name="turns")
    op.drop_table("turns")
    op.drop_index("ix_sessions_started_at", table_name="sessions")
    op.drop_index("ix_sessions_persona_phase", table_name="sessions")
    op.drop_index(op.f("ix_sessions_persona_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_invite_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_personas_area_id"), table_name="personas")
    op.drop_table("personas")
    op.drop_index(op.f("ix_interview_reports_session_id"), table_name="interview_reports")
    op.drop_index(op.f("ix_interview_reports_persona_id"), table_name="interview_reports")
    op.drop_table("interview_reports")
    op.drop_index(op.f("ix_interview_invites_slug"), table_name="interview_invites")
    op.drop_index(op.f("ix_interview_invites_persona_id"), table_name="interview_invites")
    op.drop_table("interview_invites")
    op.drop_index(op.f("ix_artifacts_session_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_areas_slug"), table_name="areas")
    op.drop_table("areas")
    # ### end Alembic commands ###
